### ISSUE TITLE
TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by hachiojidev** [pancakeswap/pancake-uikit#102]
This issue was referenced [here](https://github.com/pancakeswap/pancake-frontend/pull/205/files#r546231033)

**Comment by self-coding-crab** [comment]
Is this issue resolved?

**Comment by hachiojidev** [comment]
Closing this. The issue I believe is not from the UI Kit but from the consumer (frontend)

https://github.com/pancakeswap/pancake-frontend/pull/240
