### ISSUE TITLE
Changing the crypto wallets available when you click on connect

### ISSUE THREAD

**Issue by ryann254** [pancakeswap/pancake-uikit#195]
Mine is more of a question, is it possible to add or reduce the crypto wallets available in the pop up that appears when you click the connect?
And if so, how can one change them?
I've attached a photo of the element I'm referring to.

![Connect wallet](https://user-images.githubusercontent.com/45309245/109382753-9e1cb680-78f3-11eb-80a0-0d31088724b0.PNG)

**Comment by Chef-Chungus** [comment]
It is possible, are you building your own site?

**Comment by ryann254** [comment]
@Chef-Chungus , Yes
How would I go about it?

**Comment by RabbitDoge** [comment]
https://github.com/pancakeswap/pancake-uikit/blob/master/src/widgets/WalletModal/config.tsx
But you will need to manage the logic in the app using this component. The WalletModal component just trigger a callback with a `param:string`

**Comment by ryann254** [comment]
Okay let me try it

**Comment by RabbitDoge** [comment]
I close this since there is no more activity. Feel free to join the community slack and ask for help there if you need it.
