### ISSUE TITLE
rebuild 

### ISSUE THREAD

**Issue by arman1815** [pancakeswap/pancake-uikit#217]
hi . i clone this . with :   git clone https://github.com/pancakeswap/pancake-uikit.git
and use : yarn install 
yarn build 
 
but after rebuild . it is doesnt work . how can rebuild it .

**Comment by arman1815** [comment]
it does not work . i mean . after copy this rebuild file to /node_modules/
project doesnt show with yarn start . and show this error  
Module not found: Can't resolve '@pancake/uikit' in '/home/faramir/Downloads/thornswap-frontend/src/components/Menu

**Comment by RabbitDoge** [comment]
What are you trying to do ?

**Comment by arman1815** [comment]
it is work now . but why we cant change icon and etc easy ?

**Comment by RabbitDoge** [comment]
Our job and mission is to build Pancakeswap. We are not a service provider for people who want to fork. If you want to fork, feel free the code is available, but if you don't want to put some effort to understand the code, forget about it, we are not here to do your work.
